### ISSUE TITLE
Why box1....box28?

### ISSUE THREAD

**Issue by shibualexis** [Sathya-1992/My-Projects#1]
Why have you created a class box1,...box28? I saw you have defined grid-area. But what if you do not know the size of the image as if dynamically generated from the server side?

https://github.com/Sathya-1992/My-Projects/blob/d12c58a25743498aed3b425624412eb812f1ed49/Flickr/flickr.html#L120

**Comment by Sathya-1992** [comment]
Using these codes, to clear this issue and now didn't define that much of grid-area.
grid-template-columns: repeat(auto-fit,minmax(8rem,1fr));
    grid-auto-flow: dense;
